// Mesh Text Baker — TextLayoutEngine.cs
// Lays out TMP text for a zone and exposes the generated sub-meshes for the baker to draw
// into a RenderTexture (camera-free, via GL).
//
// Performance notes:
//   - Two reusable hidden, NON-RENDERING TextMeshPro instances are kept (one for measuring,
//     one for drawing) instead of creating/destroying a GameObject per zone. This avoids the
//     dominant per-bake cost (GameObject + TMP creation and the GC from it).
//   - The geometry of each zone is COPIED into result-owned Mesh objects (not the live shared
//     TMP mesh). This is required for correctness: the shared __MeshTextDraw TMP mesh is
//     overwritten by the next zone AND can be re-generated by an extra render pass (e.g. when
//     both the Scene and Game views render in the same frame). Drawing a live shared mesh in
//     that situation produced empty/disappearing baked text. The copied meshes are small (one
//     page of text), so the cost is negligible compared to ForceMeshUpdate.

using System;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

namespace MeshTextBaker
{
    /// <summary>One drawable piece of a zone's text: a mesh + the material to draw it with.</summary>
    public struct ZoneSubMesh
    {
        public Mesh mesh;
        public Material material;
    }

    /// <summary>Result of laying out text for a zone (copied geometry, ready to draw).</summary>
    public class ZoneLayoutResult
    {
        public ZoneSubMesh[] subMeshes;
        public string renderedText;
        public int zonePixelW;
        public int zonePixelH;
        /// <summary>Inline &lt;image=…&gt; draws resolved to mesh-local rects (may be null).</summary>
        public List<InlineImageDraw> inlineImages;
        /// <summary>Warnings produced while processing inline image tags (may be null).</summary>
        public List<string> warnings;
    }

    public static class TextLayoutEngine
    {
        private const float ReferenceResolution = 1024f;

        // Reusable hidden TMP instances (measure + draw). Renderers are disabled so they never
        // appear in the scene; we only use their generated mesh data.
        private static GameObject s_MeasureGO;
        private static TextMeshPro s_MeasureTmp;
        private static GameObject s_DrawGO;
        private static TextMeshPro s_DrawTmp;
        // Calibrations (<space> pixels-per-unit, lineSpacing pixels-per-unit) run on their
        // OWN hidden instance. Sharing the measure instance interleaved probe layouts
        // ("A\nA", wide rect) between real measurements, and TMP reuses internal buffers
        // across layouts — with ShrinkToFit's rapid measure sequence that produced a
        // period-2 limit cycle (repeated Test Bakes alternated between two layouts).
        private static GameObject s_CalibGO;
        private static TextMeshPro s_CalibTmp;

        private static bool s_CleanupHooked;

        // ── Mesh pool + reusable copy buffers (GC optimization) ──
        // A bake allocated 1 Mesh + 5 Lists per zone per bake; a book page-turn does this
        // dozens of times. Meshes are rented/returned (cleared, not destroyed) and the copy
        // buffers are reused. Everything is main-thread only, like the rest of this class.
        private static readonly System.Collections.Generic.Stack<Mesh> s_MeshPool =
            new System.Collections.Generic.Stack<Mesh>(4);
        private const int MaxPooledMeshes = 8;

        private static readonly System.Collections.Generic.List<ZoneSubMesh> s_SubMeshList = new System.Collections.Generic.List<ZoneSubMesh>(4);
        private static readonly System.Collections.Generic.List<Vector3> s_VertBuf = new System.Collections.Generic.List<Vector3>(512);
        private static readonly System.Collections.Generic.List<Color32> s_ColBuf = new System.Collections.Generic.List<Color32>(512);
        private static readonly System.Collections.Generic.List<Vector4> s_Uv0Buf = new System.Collections.Generic.List<Vector4>(512);
        private static readonly System.Collections.Generic.List<Vector4> s_Uv2Buf = new System.Collections.Generic.List<Vector4>(512);
        private static readonly System.Collections.Generic.List<int> s_TriBuf = new System.Collections.Generic.List<int>(768);

        private static Mesh RentMesh()
        {
            while (s_MeshPool.Count > 0)
            {
                var pooled = s_MeshPool.Pop();
                if (pooled != null) return pooled; // may have been destroyed externally
            }
            return new Mesh { name = "MTB_ZoneMesh", hideFlags = HideFlags.HideAndDontSave };
        }

        private static void ReturnMesh(Mesh mesh)
        {
            if (mesh == null) return;
            if (s_MeshPool.Count >= MaxPooledMeshes)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(mesh);
                else UnityEngine.Object.DestroyImmediate(mesh);
                return;
            }
            mesh.Clear();
            s_MeshPool.Push(mesh);
        }

        private static TextMeshPro GetTmpInstance(ref GameObject go, ref TextMeshPro tmp, string name)
        {
            if (tmp != null) return tmp;
            HookCleanup();
            go = new GameObject(name) { hideFlags = HideFlags.HideAndDontSave };
            tmp = go.AddComponent<TextMeshPro>();
            var r = go.GetComponent<Renderer>();
            if (r != null) r.enabled = false; // never render into the scene
            return tmp;
        }

        /// <summary>
        /// Disables ALL renderers under the hidden TMP object. TMP lazily spawns CHILD sub-mesh
        /// objects (TMP_SubMesh) for fallback fonts / sprite assets during ForceMeshUpdate; their
        /// renderers are enabled by default and would draw stray glyphs into the scene at the
        /// origin. Must be called after every ForceMeshUpdate (new children may have appeared).
        /// </summary>
        private static void DisableChildRenderers(GameObject go)
        {
            if (go == null) return;
            var renderers = go.GetComponentsInChildren<Renderer>(true);
            for (int i = 0; i < renderers.Length; i++)
                renderers[i].enabled = false;
        }

        /// <summary>Applies word-wrapping in a TMP-version-agnostic way (2022.3 LTS ↔ 2023+).</summary>
        private static void SetWordWrap(TextMeshPro tmp)
        {
#if TMP_3_2_OR_NEWER
            tmp.textWrappingMode = TextWrappingModes.Normal;
#else
            // Legacy TMP 3.0.x API (obsoleted once textWrappingMode exists).
#pragma warning disable 618
            tmp.enableWordWrapping = true;
#pragma warning restore 618
#endif
        }

        private static void HookCleanup()
        {
            if (s_CleanupHooked) return;
            s_CleanupHooked = true;
            Application.quitting += DestroyHiddenInstances;
#if UNITY_EDITOR
            UnityEditor.AssemblyReloadEvents.beforeAssemblyReload += DestroyHiddenInstances;
#endif
        }

        /// <summary>Destroys the shared hidden TMP instances (called on quit / assembly reload).</summary>
        public static void DestroyHiddenInstances()
        {
            if (s_MeasureGO != null)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(s_MeasureGO);
                else UnityEngine.Object.DestroyImmediate(s_MeasureGO);
            }
            if (s_DrawGO != null)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(s_DrawGO);
                else UnityEngine.Object.DestroyImmediate(s_DrawGO);
            }
            if (s_CalibGO != null)
            {
                if (Application.isPlaying) UnityEngine.Object.Destroy(s_CalibGO);
                else UnityEngine.Object.DestroyImmediate(s_CalibGO);
            }
            s_MeasureGO = null; s_MeasureTmp = null;
            s_DrawGO = null; s_DrawTmp = null;
            s_CalibGO = null; s_CalibTmp = null;

            InlineImageParser.ReleaseFileCache();
            InlineFontResolver.ReleaseFileCache();

            // Drop pooled meshes too — they reference the reloading domain.
            while (s_MeshPool.Count > 0)
            {
                var mesh = s_MeshPool.Pop();
                if (mesh == null) continue;
                if (Application.isPlaying) UnityEngine.Object.Destroy(mesh);
                else UnityEngine.Object.DestroyImmediate(mesh);
            }
        }

        /// <summary>
        /// Returns how many characters of 'text' fit in the slot by height, in a single TMP pass.
        /// Reads line/character info; does not collect meshes. Measurement only.
        /// </summary>
        public static int MeasureFittingChars(string text, TextZone slot, BakeSettings settings, int bakeResolution)
            => MeasureFittingChars(text, slot, settings, bakeResolution, bakeResolution, -1f);

        /// <summary>
        /// Non-square variant: measures against a WxH bake target (e.g. a custom NPOT
        /// background texture). Old square callers keep working unchanged.
        /// </summary>
        public static int MeasureFittingChars(string text, TextZone slot, BakeSettings settings,
            int bakeW, int bakeH)
            => MeasureFittingChars(text, slot, settings, bakeW, bakeH, -1f);

        /// <summary>
        /// Same as <see cref="MeasureFittingChars(string,TextZone,BakeSettings,int)"/> but with an
        /// explicit pixel font size (used by ShrinkToFit's binary search). Pass a value &lt;= 0 to
        /// use the zone's own resolved size.
        /// </summary>
        public static int MeasureFittingChars(string text, TextZone slot, BakeSettings settings,
            int bakeResolution, float pixelFontSizeOverride)
            => MeasureFittingChars(text, slot, settings, bakeResolution, bakeResolution, pixelFontSizeOverride);

        /// <summary>
        /// Same as <see cref="MeasureFittingChars(string,TextZone,BakeSettings,int,float)"/> but
        /// against a WxH bake target. Absolute font sizes scale with the LONG side.
        /// </summary>
        public static int MeasureFittingChars(string text, TextZone slot, BakeSettings settings,
            int bakeW, int bakeH, float pixelFontSizeOverride)
        {
            if (string.IsNullOrEmpty(text)) return 0;

            Rect padded = slot.GetPaddedPixelRect(bakeW, bakeH);
            int zoneW = Mathf.Max(2, Mathf.RoundToInt(padded.width));
            int zoneH = Mathf.Max(2, Mathf.RoundToInt(padded.height));

            TMP_FontAsset font = slot.fontOverride != null ? slot.fontOverride : settings.defaultFont;
            if (font == null) font = TMP_Settings.defaultFontAsset;
            if (font == null) return text.Length;

            float fontSize = pixelFontSizeOverride > 0f
                ? pixelFontSizeOverride
                : ResolveZonePixelFontSize(slot, settings, zoneH, bakeW, bakeH);

            // Inline <image> tags: measure the PROCESSED text (anchor + spacing occupy real
            // layout space) but return an index in the SOURCE string via segment mapping —
            // page slicing then keeps tags intact (book support).
            List<ImageTagSegment> imageSegments = null;
            string measured = text;
            if (slot.richTextEnabled && InlineImageParser.HasImageTags(text))
            {
                imageSegments = new List<ImageTagSegment>(4);
                float spaceFactor = GetSpacePixelFactor(font, fontSize);
                measured = InlineImageParser.ProcessWithMap(text, fontSize, settings.imageLibrary,
                    null, null, imageSegments, spaceFactor);
            }

            // Opacity is deliberately NOT expanded during measurement: alpha has no layout
            // cost, while injecting TMP <alpha> tags here would shift source indices used by
            // book pagination and inline-image segment mapping.
            var tmp = GetTmpInstance(ref s_MeasureGO, ref s_MeasureTmp, "__MeshTextMeasure");
            var rt = tmp.rectTransform;
            rt.sizeDelta = new Vector2(zoneW, zoneH);

            tmp.font = font;
            tmp.fontSize = fontSize;
            tmp.lineSpacing = ResolveLineSpacingUnits(font, fontSize, slot.lineSpacing);
            tmp.enableAutoSizing = false;
            // Measure in TopLeft space so fitting is independent of the zone's vertical anchor.
            // The final render still uses the authored Top/Middle/Bottom alignment.
            tmp.alignment = TMPro.TextAlignmentOptions.TopLeft;
            tmp.richText = slot.richTextEnabled;
            tmp.overflowMode = TextOverflowModes.Overflow;
            SetWordWrap(tmp);

            tmp.text = measured;
            tmp.ForceMeshUpdate(true);
            DisableChildRenderers(s_MeasureGO); // TMP may spawn enabled sub-mesh children

            var info = tmp.textInfo;
            if (info.characterCount == 0) return 0;
            if (info.lineCount == 0) return text.Length;

            float bottomLimit = -zoneH * 0.5f;
            float topLimit = zoneH * 0.5f;
            int lastFittingChar = -1;
            for (int li = 0; li < info.lineCount; li++)
            {
                // Checking only descender worked for Top alignment but let Bottom/Middle blocks
                // grow above the zone. Both vertical bounds must fit.
                if (info.lineInfo[li].descender < bottomLimit ||
                    info.lineInfo[li].ascender > topLimit) break;
                lastFittingChar = info.lineInfo[li].lastCharacterIndex;
            }

            if (lastFittingChar < 0) return 0;
            if (lastFittingChar >= info.characterCount - 1) return text.Length;

            int fitIndex = info.characterInfo[lastFittingChar].index + 1;
            // Map back from the processed (anchor/spacing) string to the source string.
            if (imageSegments != null)
                fitIndex = InlineImageParser.MapProcessedToSource(fitIndex, imageSegments);
            return Mathf.Clamp(fitIndex, 0, text.Length);
        }

        /// <summary>
        /// Lays out exactly the given (already-sliced) text and returns its sub-meshes in a single
        /// TMP pass, reusing a shared hidden TMP instance. The geometry is COPIED into
        /// result-owned Mesh objects (safe to draw at any time, independent of the shared TMP).
        /// Call <see cref="DisposeLayout"/> when done to free those copies.
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings, int bakeResolution)
            => BuildZoneExact(text, zone, settings, bakeResolution, -1f);

        /// <summary>
        /// Same as <see cref="BuildZoneExact(string,TextZone,BakeSettings,int)"/> but with an
        /// explicit pixel font size (used by ShrinkToFit). Pass a value &lt;= 0 to use the zone's
        /// own resolved size.
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings,
            int bakeResolution, float pixelFontSizeOverride)
            => BuildZoneExact(text, zone, settings, bakeResolution, bakeResolution, pixelFontSizeOverride, null);

        /// <summary>
        /// Non-square variant: lays out against a WxH bake target (e.g. a custom NPOT
        /// background texture). Old square callers keep working unchanged.
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings,
            int bakeW, int bakeH)
            => BuildZoneExact(text, zone, settings, bakeW, bakeH, -1f);

        /// <summary>
        /// Same as <see cref="BuildZoneExact(string,TextZone,BakeSettings,int,float)"/> but
        /// against a WxH bake target, with an explicit pixel font size (ShrinkToFit).
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings,
            int bakeW, int bakeH, float pixelFontSizeOverride)
            => BuildZoneExact(text, zone, settings, bakeW, bakeH, pixelFontSizeOverride, null);

        /// <summary>
        /// Full overload with an optional text color override (used by the emission pass to
        /// re-lay-out the same text tinted with the zone's emission color).
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings,
            int bakeResolution, float pixelFontSizeOverride, Color? textColorOverride)
            => BuildZoneExact(text, zone, settings, bakeResolution, bakeResolution,
                pixelFontSizeOverride, textColorOverride);

        /// <summary>
        /// Full non-square overload with an optional text color override (used by the
        /// emission pass to re-lay-out the same text tinted with the zone's emission color).
        /// </summary>
        public static ZoneLayoutResult BuildZoneExact(string text, TextZone zone, BakeSettings settings,
            int bakeW, int bakeH, float pixelFontSizeOverride, Color? textColorOverride)
        {
            var result = new ZoneLayoutResult { subMeshes = Array.Empty<ZoneSubMesh>(), renderedText = text ?? "" };

            Rect padded = zone.GetPaddedPixelRect(bakeW, bakeH);
            int zoneW = Mathf.Max(1, Mathf.RoundToInt(padded.width));
            int zoneH = Mathf.Max(1, Mathf.RoundToInt(padded.height));
            result.zonePixelW = zoneW;
            result.zonePixelH = zoneH;

            if (string.IsNullOrEmpty(text) || zoneW < 2 || zoneH < 2) return result;

            TMP_FontAsset font = zone.fontOverride != null ? zone.fontOverride : settings.defaultFont;
            if (font == null) font = TMP_Settings.defaultFontAsset;
            if (font == null) return result;

            float fontSize = pixelFontSizeOverride > 0f
                ? pixelFontSizeOverride
                : ResolveZonePixelFontSize(zone, settings, zoneH, bakeW, bakeH);

            // Expand opacity before image processing so anchor indices include the injected
            // alpha tags. The image parser still sees the retained mtb-opacity links and can
            // inherit their multiplier.
            text = RichTextOpacityTags.Apply(text);

            // Inline <image=...> tags → zero-width anchor chars (+ <space> when displacing).
            List<InlineImageRequest> imageRequests = null;
            if (zone.richTextEnabled && InlineImageParser.HasImageTags(text))
            {
                imageRequests = new List<InlineImageRequest>(4);
                result.warnings = new List<string>(2);
                float spaceFactor = GetSpacePixelFactor(font, fontSize);
                text = InlineImageParser.Process(text, fontSize, settings.imageLibrary,
                    imageRequests, result.warnings, spaceFactor);
                result.renderedText = text;
            }

            if (imageRequests != null)
            {
                for (int i = 0; i < imageRequests.Count; i++)
                {
                    InlineImageRequest request = imageRequests[i];
                    request.opacity *= Mathf.Clamp01(zone.opacity);
                    imageRequests[i] = request;
                }
            }
            result.renderedText = text;

            var tmp = GetTmpInstance(ref s_DrawGO, ref s_DrawTmp, "__MeshTextDraw");
            var rt = tmp.rectTransform;
            rt.sizeDelta = new Vector2(zoneW, zoneH);

            tmp.font = font;
            tmp.fontSize = fontSize;
            tmp.lineSpacing = ResolveLineSpacingUnits(font, fontSize, zone.lineSpacing);
            tmp.enableAutoSizing = false;
            tmp.alignment = zone.alignment;
            Color resolvedColor = textColorOverride
                ?? (zone.useDefaultTextColor ? settings.defaultTextColor : zone.textColor);
            resolvedColor.a *= Mathf.Clamp01(zone.opacity);
            tmp.color = resolvedColor;
            tmp.richText = zone.richTextEnabled;
            tmp.overflowMode = TextOverflowModes.Overflow;
            SetWordWrap(tmp);

            tmp.text = text;
            tmp.ForceMeshUpdate(true); // single pass; reused component
            DisableChildRenderers(s_DrawGO); // TMP may spawn enabled sub-mesh children

            // Resolve inline image anchors → mesh-local rects (anchor char origin/baseline).
            if (imageRequests != null && imageRequests.Count > 0)
                result.inlineImages = ResolveInlineImages(tmp, imageRequests, fontSize);

            int meshCount = tmp.textInfo?.meshInfo?.Length ?? 0;
            var list = s_SubMeshList;
            list.Clear();
            for (int m = 0; m < meshCount; m++)
            {
                var mi = tmp.textInfo.meshInfo[m];
                if (mi.vertexCount == 0) continue;
                Material mat = mi.material != null ? mi.material : font.material;
                if (mat == null) continue;

                // Copy the generated geometry into a pooled, result-owned mesh. We must NOT
                // keep a reference to the shared TMP mesh (mi.mesh): it gets overwritten by the
                // next zone and can be regenerated by an additional render pass (Scene + Game
                // views), which made the baked text vanish. The copy is cheap (one page).
                //
                // Copy element-by-element (NOT Array.Copy). TMP's meshInfo arrays can have a
                // runtime element type that Array.Copy rejects with ArrayTypeMismatchException,
                // so we copy values explicitly into reusable, correctly-typed buffers.
                int vCount = mi.vertexCount;
                int tCount = (vCount / 4) * 6; // TMP geometry is quad-based (4 verts -> 6 indices)

                var verts = s_VertBuf; verts.Clear();
                var cols = s_ColBuf; cols.Clear();
                var uv0 = s_Uv0Buf; uv0.Clear();
                var uv2 = s_Uv2Buf; uv2.Clear();

                var srcVerts = mi.vertices;
                var srcCols = mi.colors32;
                var srcUv0 = mi.uvs0;
                var srcUv2 = mi.uvs2;
                bool hasCols = srcCols != null && srcCols.Length >= vCount;
                bool hasUv0 = srcUv0 != null && srcUv0.Length >= vCount;
                bool hasUv2 = srcUv2 != null && srcUv2.Length >= vCount;

                for (int v = 0; v < vCount; v++)
                {
                    verts.Add(srcVerts[v]);
                    cols.Add(hasCols ? srcCols[v] : (Color32)Color.white);
                    uv0.Add(hasUv0 ? srcUv0[v] : Vector4.zero);
                    uv2.Add(hasUv2 ? srcUv2[v] : Vector4.zero);
                }

                var tris = s_TriBuf; tris.Clear();
                var srcTris = mi.triangles;
                int copyTris = (srcTris != null) ? Mathf.Min(tCount, srcTris.Length) : 0;
                for (int t = 0; t < copyTris; t++)
                    tris.Add(srcTris[t]);

                var meshCopy = RentMesh();
                meshCopy.SetVertices(verts);
                meshCopy.SetColors(cols);
                meshCopy.SetUVs(0, uv0);
                meshCopy.SetUVs(1, uv2);
                meshCopy.SetTriangles(tris, 0, false);
                meshCopy.RecalculateBounds();

                list.Add(new ZoneSubMesh { mesh = meshCopy, material = mat });
            }
            result.subMeshes = list.ToArray();
            list.Clear();
            return result;
        }

        /// <summary>
        /// Releases the result-owned mesh copies back to the internal pool (cleared and reused
        /// by the next zone). The shared TMP instances are NOT destroyed.
        /// </summary>
        public static void DisposeLayout(ZoneLayoutResult result)
        {
            if (result == null || result.subMeshes == null) return;
            for (int i = 0; i < result.subMeshes.Length; i++)
                ReturnMesh(result.subMeshes[i].mesh);
            result.subMeshes = Array.Empty<ZoneSubMesh>();
        }

        /// <summary>
        /// Maps each image request's anchor character (U+200B, located by its index in the
        /// SOURCE string) to a rect in the TMP mesh's local space. The image sits on the
        /// anchor's baseline, extending right by width and up by height.
        /// </summary>
        private static List<InlineImageDraw> ResolveInlineImages(TextMeshPro tmp,
            List<InlineImageRequest> requests, float fontSizePx)
        {
            var info = tmp.textInfo;
            if (info == null || info.characterCount == 0) return null;

            var draws = new List<InlineImageDraw>(requests.Count);

            for (int r = 0; r < requests.Count; r++)
            {
                var req = requests[r];

                // Find the laid-out character whose SOURCE index matches the anchor.
                // (characterInfo[i].index is the index into the original string; rich-text
                // tags are skipped by the layout, so a linear scan is required.)
                int found = -1;
                for (int c = 0; c < info.characterCount; c++)
                {
                    if (info.characterInfo[c].index == req.anchorIndex)
                    {
                        found = c;
                        break;
                    }
                }
                if (found < 0) continue; // anchor clipped/overflowed — image not visible

                var ci = info.characterInfo[found];
                InlineImageParser.GetPixelSize(req, fontSizePx, out float wPx, out float hPx);

                // Pivot-anchored rect at the anchor's origin/baseline: pivot (0,0) puts the
                // image's bottom-left there (default); (0.5,0.5) centers it on the point etc.
                float x = ci.origin - wPx * req.pivot.x;
                float y = ci.baseLine - hPx * req.pivot.y;
                draws.Add(new InlineImageDraw
                {
                    texture = req.texture,
                    localRect = new Rect(x, y, wPx, hPx),
                    underText = req.underText,
                    // PBR scope info MUST travel with the draw — the baker filters images
                    // in emission/mask passes by it (missing this was the "images ignore
                    // PBR tags entirely" bug: scope stayed None and every image was culled).
                    scope = req.scope,
                    scopeColorHex = req.scopeColorHex,
                    scopeIntensity = req.scopeIntensity,
                    scopeMetallic = req.scopeMetallic,
                    scopeSmoothness = req.scopeSmoothness,
                    scopeHeight = req.scopeHeight,
                    hasBlendMode = req.hasBlendMode,
                    blendMode = req.blendMode,
                    opacity = req.opacity
                });
            }
            return draws.Count > 0 ? draws : null;
        }

        // ── <space> calibration for inline images ──────────────────────────────────
        // The pixel effect of TMP's <space=N> depends on the component's internal scale.
        // We measure it ONCE per (font, fontSize): lay out "A<space=100>A" and compare the
        // second glyph's origin against "AA". factor = (shifted - base) / 100 → pixels per
        // requested unit. Cached; cheap (two tiny layouts on the shared measure TMP).
        private static TMP_FontAsset s_SpaceCalibFont;
        private static float s_SpaceCalibSize = -1f;
        private static float s_SpaceCalibFactor = 1f;

        private static float GetSpacePixelFactor(TMP_FontAsset font, float fontSizePx)
        {
            if (s_SpaceCalibFont == font && Mathf.Approximately(s_SpaceCalibSize, fontSizePx))
                return s_SpaceCalibFactor;

            var tmp = GetTmpInstance(ref s_CalibGO, ref s_CalibTmp, "__MeshTextCalib");
            tmp.rectTransform.sizeDelta = new Vector2(4096, 512); // wide: no wrapping
            tmp.font = font;
            tmp.fontSize = fontSizePx;
            tmp.enableAutoSizing = false;
            tmp.alignment = TMPro.TextAlignmentOptions.TopLeft;
            tmp.richText = true;
            tmp.overflowMode = TextOverflowModes.Overflow;
            SetWordWrap(tmp);

            float baseline = MeasureSecondGlyphOrigin(tmp, "AA");
            float shifted = MeasureSecondGlyphOrigin(tmp, "A<space=100>A");
            DisableChildRenderers(s_CalibGO);

            float delta = shifted - baseline;
            s_SpaceCalibFactor = delta > 0.001f ? delta / 100f : 1f;
            s_SpaceCalibFont = font;
            s_SpaceCalibSize = fontSizePx;
            return s_SpaceCalibFactor;
        }

        private static float MeasureSecondGlyphOrigin(TextMeshPro tmp, string sample)
        {
            tmp.text = sample;
            tmp.ForceMeshUpdate(true);
            var info = tmp.textInfo;
            return info.characterCount >= 2 ? info.characterInfo[1].origin : 0f;
        }

        // ── lineSpacing calibration ──────────────────────────────────────────────
        // TMP's lineSpacing units depend on the TMP version and the font asset, so we
        // calibrate like <space>: lay out two lines with spacing 0 vs 100 and divide the
        // second line's shift by 100 → pixels (TMP-local units map 1:1 to bake pixels)
        // per lineSpacing unit. Cached per (font, fontSize); skipped entirely while the
        // zone keeps the default 0 (zero overhead, zero behavior change).
        private static TMP_FontAsset s_LineCalibFont;
        private static float s_LineCalibSize = -1f;
        private static float s_LineCalibFactor = 1f;

        private static float ResolveLineSpacingUnits(TMP_FontAsset font, float fontSizePx, float extraPixels)
        {
            if (Mathf.Approximately(extraPixels, 0f)) return 0f;
            return extraPixels / GetLineSpacingPixelFactor(font, fontSizePx);
        }

        private static float GetLineSpacingPixelFactor(TMP_FontAsset font, float fontSizePx)
        {
            if (s_LineCalibFont == font && Mathf.Approximately(s_LineCalibSize, fontSizePx))
                return s_LineCalibFactor;

            var tmp = GetTmpInstance(ref s_CalibGO, ref s_CalibTmp, "__MeshTextCalib");
            tmp.rectTransform.sizeDelta = new Vector2(4096, 512); // wide: no wrapping
            tmp.font = font;
            tmp.fontSize = fontSizePx;
            tmp.enableAutoSizing = false;
            tmp.alignment = TMPro.TextAlignmentOptions.TopLeft;
            tmp.richText = true;
            tmp.overflowMode = TextOverflowModes.Overflow;
            SetWordWrap(tmp);

            float baseline = MeasureSecondLineTop(tmp, 0f);
            float shifted = MeasureSecondLineTop(tmp, 100f);
            tmp.lineSpacing = 0f; // dedicated instance, but leave no residue anyway
            DisableChildRenderers(s_CalibGO);

            float delta = Mathf.Abs(shifted - baseline);
            s_LineCalibFactor = delta > 0.001f ? delta / 100f : 1f;
            s_LineCalibFont = font;
            s_LineCalibSize = fontSizePx;
            return s_LineCalibFactor;
        }

        private static float MeasureSecondLineTop(TextMeshPro tmp, float spacing)
        {
            tmp.lineSpacing = spacing;
            tmp.text = "A\nA";
            tmp.ForceMeshUpdate(true);
            var info = tmp.textInfo;
            return info.lineCount >= 2 ? info.lineInfo[1].ascender : 0f;
        }

        // bakeLongSide: the LONG side of the bake target in pixels. Absolute font sizes
        // scale with it, so type keeps its size whether the target is square or not.
        private static float ResolvePixelFontSize(float value, FontSizeMode mode, int zoneHeightPx, int bakeLongSide)
        {
            if (value <= 0f) value = 1f;
            return mode == FontSizeMode.PercentOfZoneHeight
                ? Mathf.Max(1f, (value / 100f) * zoneHeightPx)
                : Mathf.Max(1f, value * (bakeLongSide / ReferenceResolution));
        }

        /// <summary>Resolves the zone's effective font size in PIXELS at the given bake resolution.</summary>
        public static float ResolveZonePixelFontSize(TextZone zone, BakeSettings settings, int zoneHeightPx, int bakeResolution)
            => ResolveZonePixelFontSize(zone, settings, zoneHeightPx, bakeResolution, bakeResolution);

        /// <summary>
        /// Non-square variant: absolute font sizes scale with the LONG side of the WxH target.
        /// </summary>
        public static float ResolveZonePixelFontSize(TextZone zone, BakeSettings settings,
            int zoneHeightPx, int bakeW, int bakeH)
        {
            bool hasZoneSize = zone.fontSize > 0f;
            float rawSize = hasZoneSize ? zone.fontSize : settings.defaultFontSize;
            FontSizeMode mode = hasZoneSize ? zone.fontSizeMode : settings.defaultFontSizeMode;
            return ResolvePixelFontSize(rawSize, mode, zoneHeightPx, Mathf.Max(bakeW, bakeH));
        }

        /// <summary>
        /// ShrinkToFit: binary-searches the largest pixel font size in
        /// [fontSizeMin, fontSizeMax] (interpreted via the zone's FontSizeMode) at which the whole
        /// text fits the zone. Returns the found pixel size, or the minimum if nothing fits.
        /// </summary>
        public static float FindShrinkToFitPixelSize(string text, TextZone zone, BakeSettings settings, int bakeResolution)
            => FindShrinkToFitPixelSize(text, zone, settings, bakeResolution, bakeResolution);

        /// <summary>
        /// Non-square variant of the ShrinkToFit search (see the square overload). Absolute
        /// font sizes scale with the LONG side of the WxH target.
        /// </summary>
        public static float FindShrinkToFitPixelSize(string text, TextZone zone, BakeSettings settings,
            int bakeW, int bakeH)
        {
            Rect padded = zone.GetPaddedPixelRect(bakeW, bakeH);
            int zoneH = Mathf.Max(2, Mathf.RoundToInt(padded.height));

            int longSide = Mathf.Max(bakeW, bakeH);
            float startPx = ResolveZonePixelFontSize(zone, settings, zoneH, bakeW, bakeH);
            FontSizeMode effectiveMode = zone.fontSize > 0f
                ? zone.fontSizeMode : settings.defaultFontSizeMode;
            float minPx = ResolvePixelFontSize(Mathf.Max(0.01f, zone.fontSizeMin), effectiveMode, zoneH, longSide);
            float maxPx = ResolvePixelFontSize(Mathf.Max(zone.fontSizeMin, zone.fontSizeMax), effectiveMode, zoneH, longSide);

            // The zone's own size acts as the upper bound if it lies inside [min, max].
            float hi = Mathf.Clamp(startPx, minPx, maxPx);
            float lo = minPx;

            if (string.IsNullOrEmpty(text)) return hi;

            // Fast path: fits at the desired size already.
            if (MeasureFittingChars(text, zone, settings, bakeW, bakeH, hi) >= text.Length)
                return hi;

            // Binary search (~7 iterations gives sub-pixel precision on any sane range).
            float best = lo;
            for (int it = 0; it < 8 && hi - lo > 0.25f; it++)
            {
                float mid = (lo + hi) * 0.5f;
                if (MeasureFittingChars(text, zone, settings, bakeW, bakeH, mid) >= text.Length)
                {
                    best = mid;
                    lo = mid;
                }
                else
                {
                    hi = mid;
                }
            }
            return Mathf.Max(minPx, best);
        }
    }
}
